### ISSUE TITLE
PDF build fails with xelatex missing on OSX

### ISSUE THREAD

**Issue by cansik** [patriciogonzalezvivo/thebookofshaders#13]
Creating this PDF is really not for beginners. I started with my last post #12 . Now let's try to really build a pdf out of the .text file.
## The simple way

Waiiiiit, maybe you just want that pdf, doesn't matter if you built it your own! So please choose the simple way and download it from here:

[The Book Of Shaders PDF](http://easyguet.ch/temp/thebookofshaders.pdf)
#### Install xelatex

The **parseBook.py** always told me:

```
Successful building of ./book.tex
pandoc: xelatex not found. xelatex is needed for pdf output.
Error in building of ./book.pdf
```

I couldn't find xelatex on brew so I asked google and google said, port it (it's a monster package):

```
sudo port install texlive-xetex
```
#### Fix latex imports

After installing it, let's try the building again:

```
Successful building of ./book.tex
pandoc: Could not find image `matrixes.png', skipping...
pandoc: Could not find image `warmerdam.jpg', skipping...
pandoc: Could not find image `tartan.jpg', skipping...
pandoc: Could not find image `ryoji-ikeda.jpg', skipping...
! LaTeX Error: File `lmodern.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 

l.3 \usepackage

pandoc: Error producing PDF from TeX source
Error in building of ./book.pdf
```

Thank you [University of Nebraska-Lincoln](http://mirror.unl.edu/ctan/fonts/lm/tex/latex/lm/lmodern.sty) because they were hosting the `lmodern.sty`. Now building again:

```
! LaTeX Error: File `etoolbox.sty' not found.
```

Fix it with [ctan.org/.../etoolbox](https://www.ctan.org/tex-archive/macros/latex/contrib/etoolbox?lang=en) and run it again...
#### Fix Font support

```
! Font EU1/lmr/m/n/10=[lmroman10-regular]:mapping=tex-text at 10.0pt not loadable: Metric (TFM) file or installed font not found.
```

Ok..come on! -.-

```
sudo port install texlive-fonts-recommended
```
#### Fix bad parsing in .tmp files

Wuhu, the font is now installed...but:

```
pandoc: Could not find image `matrixes.png', skipping...
pandoc: Could not find image `warmerdam.jpg', skipping...
pandoc: Could not find image `tartan.jpg', skipping...
pandoc: Could not find image `ryoji-ikeda.jpg', skipping...
! Unable to load picture or PDF file 'matrixes.png'.
<to be read again> 
                   }
l.2654 .../Matrix}{\includegraphics{matrixes.png}}
```

So maybe we have to care about the skipped files. Looks like there is something wrong..(or it's me not able to read md..) (maybe again a parsing error) (I'll fix this later...):

``` markdown
[![Wikipedia entry for Matrix (mathematics) ](matrixes.png)](./08/https://en.wikipedia.org/wiki/Matrix)
```

Change it to in the relevant .tmp file in the chapter folders:

``` markdown
[![Wikipedia entry for Matrix (mathematics) ](./08/matrixes.png)](https://en.wikipedia.org/wiki/Matrix)
```

Do this for every file which is skipped at the beginning! Now build it again...

Tadaaaaaaaaa! We've built the book of shaders! It's not perfect, some images overlay the text, but it's finally done.

Maybe we should write a book about building the book of shaders...

**Comment by MartinRGB** [comment]
My OS is Mac OS X,to solve this,you need:

1.Deal with xelatex:

- Download [BasicTex](http://www.tug.org/mactex/morepackages.html),then install the `.pkg` file
- in terminal, `tlmgr update --self`
- then `tlmgr install collection-fontsrecommended`

this part you can reference [here](https://pandoc.org/installing.html)

2.Define the path

- In terminal,`open -e ~/.bash_profile`
- add `export PATH=/Library/TeX/texbin:$PATH`,save & quit;
- in terminal,`source ~/.bash_profile`

this part you can reference [here](https://stackoverflow.com/questions/37208051/pandoc-xelatex-not-found-xelatex-is-needed-for-pdf-output)

3.'Dimension is too large!'

If you `make` now, you will meet 'Dimension is too large'  problem,the problem is happened in Folder 12

To solve this:

- Direct into Folder `12`,Choose all the image file,open in Preview app,
- Select all files, `Tools -> Adjust Size`(I set 50% scale)

4.Open terminal,press 'make',wait for a moments,all will be done!

**Comment by unixzii** [comment]
Good job!

**Comment by yvan-sraka** [comment]
Hello @cansik, what do you think about moving the instructions of this issue and https://github.com/patriciogonzalezvivo/thebookofshaders/issues/12 as a FAQ item at the end of Appendix 2 and close those two issues :wink:?

**Comment by cansik** [comment]
@yvan-sraka Sounds good :)

**Comment by clankill3r** [comment]
Thanks for the pdf. Building the pdf myself is such a pain where it goes from fixing one error to the next error...
