### ISSUE TITLE
Dark web tactics?

### ISSUE THREAD

**Issue by AdditionAddict** [patriciogonzalezvivo/thebookofshaders#404]
Was happy to donate but the donate page made me think I'd be getting the whole book

"Donate money to complete The Book of Shaders TheBookOfShaders"

I read that literally. I.e. donate and I'd get the chapters "Image processing" etc

**Comment by patriciogonzalezvivo** [comment]
"Dark web tactics" Really?

The book was released in 2015 and have been up and growing since then. The project is very transparent on where is it now and how to contribute. The proof of that is that you came here, to it's repository and where able, not only to see it's entire source code, but also leave this message.

**Comment by AdditionAddict** [comment]
@patriciogonzalezvivo 

> The book was released in 2015 and have been up and growing since then. 

Not relevant

> The project is very transparent on where is it now and how to contribute. The proof of that is that you came here, to it's repository and where able, not only to see it's entire source code, but also leave this message.

Only after realising. I thought you'd be unhappy that people may do the same and wanted to feed this back.

I suggest changing "Donate money to complete" to something along the line "Donate money to support the authors".

But you'd rather take offence than feedback I guess 🤷‍♂️

**Comment by patriciogonzalezvivo** [comment]
sorry but "Dark web tactics" it's pretty offensive
