### ISSUE TITLE
README-ch.md should be renamed to README-cn.md

### ISSUE THREAD

**Issue by cclauss** [patriciogonzalezvivo/thebookofshaders#84]
CH == Switzerland
CN = China

**Comment by patriciogonzalezvivo** [comment]
Hi, 'ch' in this case referees to Chinese. For translating the book, a clear way to referring to a language was chosen over countries. Specially because several countries can share a single language. For example: Spanish is the primary language on most countries in Latin America is usually usually denoted as 'es' from 'español'.

If you are interested on translating a chapter to any of the official Switzerland languages like Romansh, German, French or Italian let me know. There is an Italian and French translation in progress but help will be welcome. : )

Best,

**Comment by cclauss** [comment]
Of course, ISO has standard abbreviations for such things.
https://en.m.wikipedia.org/wiki/ISO_639-1  Says zh instead of either ch or cn.
Given that English is my mother tongue ,, zh is not intuitive to me but perhaps it is to Chinese speaker.
I
